from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
REPORTS_DIR = PROJECT_ROOT / "reports"


HISTORICAL_SOURCES = [
    ("SP1", "2016/17", RAW_DIR / "laliga" / "SP1_2016_17.csv"),
    ("SP1", "2017/18", RAW_DIR / "laliga" / "SP1_2017_18.csv"),
    ("SP1", "2018/19", RAW_DIR / "laliga" / "SP1_2018_19.csv"),
    ("SP1", "2019/20", RAW_DIR / "laliga" / "SP1_2019_20.csv"),
    ("SP1", "2020/21", RAW_DIR / "laliga" / "SP1_2020_21.csv"),
    ("SP1", "2021/22", RAW_DIR / "laliga" / "SP1_2021_22.csv"),
    ("SP1", "2022/23", RAW_DIR / "laliga" / "SP1_2022_23.csv"),
    ("SP1", "2023/24", RAW_DIR / "laliga" / "SP1_2023_24.csv"),
    ("SP1", "2024/25", RAW_DIR / "laliga" / "SP1_2024_25.csv"),
    ("SP1", "2025/26", RAW_DIR / "laliga" / "SP1_2025_26.csv"),
    ("SP2", "2021/22", RAW_DIR / "segunda" / "SP2_2021_22.csv"),
    ("SP2", "2022/23", RAW_DIR / "segunda" / "SP2_2022_23.csv"),
    ("SP2", "2023/24", RAW_DIR / "segunda" / "SP2_2023_24.csv"),
    ("SP2", "2024/25", RAW_DIR / "segunda" / "SP2_2024_25.csv"),
    ("SP2", "2025/26", RAW_DIR / "segunda" / "SP2_2025_26.csv"),
]

FIXTURE_SOURCE = RAW_DIR / "fixtures" / "laliga_2026_27.csv"


TEAM_NAMES = {
    "alaves": "Deportivo Alavés",
    "albacete": "Albacete Balompié",
    "alcorcon": "AD Alcorcón",
    "almeria": "UD Almería",
    "amorebieta": "SD Amorebieta",
    "andorra": "FC Andorra",
    "athletic_bilbao": "Athletic Club",
    "atletico_madrid": "Atlético de Madrid",
    "barcelona": "FC Barcelona",
    "betis": "Real Betis",
    "burgos": "Burgos CF",
    "cadiz": "Cádiz CF",
    "cartagena": "FC Cartagena",
    "castellon": "CD Castellón",
    "celta": "RC Celta",
    "ceuta": "AD Ceuta FC",
    "cordoba": "Córdoba CF",
    "cultural_leonesa": "Cultural Leonesa",
    "deportivo": "RC Deportivo",
    "eibar": "SD Eibar",
    "elche": "Elche CF",
    "eldense": "CD Eldense",
    "espanyol": "RCD Espanyol",
    "ferrol": "Racing de Ferrol",
    "fuenlabrada": "CF Fuenlabrada",
    "getafe": "Getafe CF",
    "girona": "Girona FC",
    "granada": "Granada CF",
    "huesca": "SD Huesca",
    "ibiza": "UD Ibiza",
    "las_palmas": "UD Las Palmas",
    "leganes": "CD Leganés",
    "levante": "Levante UD",
    "lugo": "CD Lugo",
    "malaga": "Málaga CF",
    "mallorca": "RCD Mallorca",
    "mirandes": "CD Mirandés",
    "osasuna": "CA Osasuna",
    "oviedo": "Real Oviedo",
    "ponferradina": "SD Ponferradina",
    "racing_santander": "Racing de Santander",
    "real_madrid": "Real Madrid",
    "real_sociedad": "Real Sociedad",
    "real_sociedad_b": "Real Sociedad B",
    "sevilla": "Sevilla FC",
    "sporting_gijon": "Sporting de Gijón",
    "tenerife": "CD Tenerife",
    "valencia": "Valencia CF",
    "valladolid": "Real Valladolid",
    "vallecano": "Rayo Vallecano",
    "villarreal": "Villarreal CF",
    "villarreal_b": "Villarreal B",
    "zaragoza": "Real Zaragoza",
}


TEAM_ALIASES = {
    # Football-Data names
    "Alaves": "alaves",
    "Albacete": "albacete",
    "Alcorcon": "alcorcon",
    "Almeria": "almeria",
    "Amorebieta": "amorebieta",
    "Andorra": "andorra",
    "Ath Bilbao": "athletic_bilbao",
    "Ath Madrid": "atletico_madrid",
    "Barcelona": "barcelona",
    "Betis": "betis",
    "Burgos": "burgos",
    "Cadiz": "cadiz",
    "Cartagena": "cartagena",
    "Castellon": "castellon",
    "Celta": "celta",
    "Ceuta": "ceuta",
    "Cordoba": "cordoba",
    "Cultural Leonesa": "cultural_leonesa",
    "Eibar": "eibar",
    "Elche": "elche",
    "Eldense": "eldense",
    "Espanol": "espanyol",
    "Ferrol": "ferrol",
    "Fuenlabrada": "fuenlabrada",
    "Getafe": "getafe",
    "Girona": "girona",
    "Granada": "granada",
    "Huesca": "huesca",
    "Ibiza": "ibiza",
    "La Coruna": "deportivo",
    "Las Palmas": "las_palmas",
    "Leganes": "leganes",
    "Levante": "levante",
    "Lugo": "lugo",
    "Malaga": "malaga",
    "Mallorca": "mallorca",
    "Mirandes": "mirandes",
    "Osasuna": "osasuna",
    "Oviedo": "oviedo",
    "Ponferradina": "ponferradina",
    "Real Madrid": "real_madrid",
    "Santander": "racing_santander",
    "Sevilla": "sevilla",
    "Sociedad": "real_sociedad",
    "Sociedad B": "real_sociedad_b",
    "Sp Gijon": "sporting_gijon",
    "Tenerife": "tenerife",
    "Valencia": "valencia",
    "Valladolid": "valladolid",
    "Vallecano": "vallecano",
    "Villarreal": "villarreal",
    "Villarreal B": "villarreal_b",
    "Zaragoza": "zaragoza",
    # Official calendar names
    "Athletic Club": "athletic_bilbao",
    "Atlético de Madrid": "atletico_madrid",
    "CA Osasuna": "osasuna",
    "Deportivo Alavés": "alaves",
    "Elche CF": "elche",
    "FC Barcelona": "barcelona",
    "Getafe CF": "getafe",
    "Levante UD": "levante",
    "Málaga CF": "malaga",
    "R. Racing Club": "racing_santander",
    "RC Celta": "celta",
    "RC Deportivo": "deportivo",
    "RCD Espanyol de Barcelona": "espanyol",
    "Rayo Vallecano": "vallecano",
    "Real Betis": "betis",
    "Real Sociedad": "real_sociedad",
    "Sevilla FC": "sevilla",
    "Valencia CF": "valencia",
    "Villarreal CF": "villarreal",
}


SOURCE_TO_MASTER = {
    "Div": "division",
    "Date": "date",
    "Time": "kickoff_time",
    "HomeTeam": "home_team_raw",
    "AwayTeam": "away_team_raw",
    "FTHG": "home_goals",
    "FTAG": "away_goals",
    "FTR": "result",
    "HTHG": "home_goals_ht",
    "HTAG": "away_goals_ht",
    "HTR": "result_ht",
    "Referee": "referee",
    "HS": "home_shots",
    "AS": "away_shots",
    "HST": "home_shots_on_target",
    "AST": "away_shots_on_target",
    "HF": "home_fouls",
    "AF": "away_fouls",
    "HC": "home_corners",
    "AC": "away_corners",
    "HY": "home_yellow_cards",
    "AY": "away_yellow_cards",
    "HR": "home_red_cards",
    "AR": "away_red_cards",
    "B365H": "odds_b365_home",
    "B365D": "odds_b365_draw",
    "B365A": "odds_b365_away",
    "AvgH": "odds_avg_home",
    "AvgD": "odds_avg_draw",
    "AvgA": "odds_avg_away",
    "MaxH": "odds_max_home",
    "MaxD": "odds_max_draw",
    "MaxA": "odds_max_away",
}


NUMERIC_MASTER_COLUMNS = [
    "home_goals",
    "away_goals",
    "home_goals_ht",
    "away_goals_ht",
    "home_shots",
    "away_shots",
    "home_shots_on_target",
    "away_shots_on_target",
    "home_fouls",
    "away_fouls",
    "home_corners",
    "away_corners",
    "home_yellow_cards",
    "away_yellow_cards",
    "home_red_cards",
    "away_red_cards",
    "odds_b365_home",
    "odds_b365_draw",
    "odds_b365_away",
    "odds_avg_home",
    "odds_avg_draw",
    "odds_avg_away",
    "odds_max_home",
    "odds_max_draw",
    "odds_max_away",
]
